version: '3.3'
services:

  frontend:
    image: thelie/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/

  db:
    image: postgres:14.4-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: thelie/foodgram_backend:latest
    restart: always
    command: >
      bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0:8000 foodgram.wsgi"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.23.0-alpine
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  postgres_data: